// Mock data for services
export function getServices() {
  return [
    {
      id: "1",
      name: "Pixel Perfect Photography",
      category: "cameras",
      description:
        "Professional photography services for weddings, corporate events, and special occasions. Our team of experienced photographers will capture your special moments with high-quality equipment and artistic vision.",
      price: 25000,
      rating: 4.8,
      reviewCount: 45,
      location: "Indiranagar",
      duration: "4-8 hours",
      capacity: "Any",
      featured: true,
      image: "/placeholder.svg?height=300&width=500&text=Pixel+Perfect+Photography",
      images: [
        "/placeholder.svg?height=600&width=800&text=Photography+Sample+1",
        "/placeholder.svg?height=600&width=800&text=Photography+Sample+2",
        "/placeholder.svg?height=600&width=800&text=Photography+Sample+3",
        "/placeholder.svg?height=600&width=800&text=Photography+Sample+4",
      ],
      reviews: [
        {
          id: "r1",
          user: { name: "Rahul S.", avatar: "/placeholder.svg" },
          rating: 5,
          comment:
            "Amazing service! The photographers were professional and captured all the special moments of our wedding in Bangalore.",
          date: "May 15, 2023",
        },
        {
          id: "r2",
          user: { name: "Priya M.", avatar: "/placeholder.svg" },
          rating: 4,
          comment: "Great photos, but wish we had more time with the photographer.",
          date: "April 22, 2023",
        },
      ],
    },
    {
      id: "2",
      name: "Bangalore Palace Convention Center",
      category: "halls",
      description:
        "Elegant and spacious convention hall perfect for large events, weddings, and corporate functions in the heart of Bangalore. Features state-of-the-art sound systems, customizable lighting, and catering options.",
      price: 150000,
      rating: 4.5,
      reviewCount: 32,
      location: "Palace Grounds",
      duration: "Full day",
      capacity: "500",
      featured: true,
      image: "/placeholder.svg?height=300&width=500&text=Bangalore+Palace+Convention",
      images: [
        "/placeholder.svg?height=600&width=800&text=Convention+Hall+1",
        "/placeholder.svg?height=600&width=800&text=Convention+Hall+2",
        "/placeholder.svg?height=600&width=800&text=Convention+Hall+3",
        "/placeholder.svg?height=600&width=800&text=Convention+Hall+4",
      ],
      reviews: [
        {
          id: "r3",
          user: { name: "Vikram R.", avatar: "/placeholder.svg" },
          rating: 5,
          comment: "Perfect venue for our corporate event. Staff was helpful and the facilities were excellent.",
          date: "June 10, 2023",
        },
      ],
    },
    {
      id: "3",
      name: "Mysore Silk Decorators",
      category: "decorators",
      description:
        "Beautiful floral arrangements and traditional Bangalore-style decorations for any event. Our expert decorators create stunning centerpieces, mandaps, and venue decorations using fresh, seasonal flowers and traditional elements.",
      price: 35000,
      rating: 4.9,
      reviewCount: 56,
      location: "Jayanagar",
      duration: "Setup day before event",
      capacity: "Any",
      featured: true,
      image: "/placeholder.svg?height=300&width=500&text=Mysore+Silk+Decorators",
      images: [
        "/placeholder.svg?height=600&width=800&text=Decoration+Sample+1",
        "/placeholder.svg?height=600&width=800&text=Decoration+Sample+2",
        "/placeholder.svg?height=600&width=800&text=Decoration+Sample+3",
        "/placeholder.svg?height=600&width=800&text=Decoration+Sample+4",
      ],
      reviews: [
        {
          id: "r4",
          user: { name: "Anjali L.", avatar: "/placeholder.svg" },
          rating: 5,
          comment:
            "The decorations were absolutely gorgeous! Everyone at our wedding was impressed with the traditional Bangalore style.",
          date: "May 30, 2023",
        },
      ],
    },
    {
      id: "4",
      name: "Budget Clicks Photography",
      category: "cameras",
      description:
        "Affordable photography services for small events and gatherings. Quality photos without breaking the bank.",
      price: 15000,
      rating: 4.2,
      reviewCount: 28,
      location: "Koramangala",
      duration: "2-4 hours",
      capacity: "Any",
      featured: false,
      image: "/placeholder.svg?height=300&width=500&text=Budget+Clicks",
      images: [
        "/placeholder.svg?height=600&width=800&text=Budget+Photo+1",
        "/placeholder.svg?height=600&width=800&text=Budget+Photo+2",
        "/placeholder.svg?height=600&width=800&text=Budget+Photo+3",
        "/placeholder.svg?height=600&width=800&text=Budget+Photo+4",
      ],
      reviews: [],
    },
    {
      id: "5",
      name: "Whitefield Conference Center",
      category: "halls",
      description:
        "Modern conference facility ideal for business meetings, workshops, and small gatherings in Bangalore's tech hub. Equipped with projector, whiteboard, and high-speed internet.",
      price: 50000,
      rating: 4.0,
      reviewCount: 15,
      location: "Whitefield",
      duration: "Half day or full day",
      capacity: "150",
      featured: false,
      image: "/placeholder.svg?height=300&width=500&text=Whitefield+Conference",
      images: [
        "/placeholder.svg?height=600&width=800&text=Conference+Room+1",
        "/placeholder.svg?height=600&width=800&text=Conference+Room+2",
        "/placeholder.svg?height=600&width=800&text=Conference+Room+3",
        "/placeholder.svg?height=600&width=800&text=Conference+Room+4",
      ],
      reviews: [],
    },
    {
      id: "6",
      name: "Simple Elegance Decorators",
      category: "decorators",
      description:
        "Simple and elegant decoration services for events on a budget in Bangalore. Includes basic table settings, backdrop, and minimal floral arrangements.",
      price: 20000,
      rating: 4.3,
      reviewCount: 22,
      location: "Marathahalli",
      duration: "Setup on event day",
      capacity: "Any",
      featured: false,
      image: "/placeholder.svg?height=300&width=500&text=Simple+Elegance",
      images: [
        "/placeholder.svg?height=600&width=800&text=Simple+Decor+1",
        "/placeholder.svg?height=600&width=800&text=Simple+Decor+2",
        "/placeholder.svg?height=600&width=800&text=Simple+Decor+3",
        "/placeholder.svg?height=600&width=800&text=Simple+Decor+4",
      ],
      reviews: [],
    },
    {
      id: "7",
      name: "Cinematic Moments",
      category: "cameras",
      description:
        "Premium videography services with top-of-the-line equipment and a team of award-winning cinematographers in Bangalore. Includes drone footage, same-day edits, and a photo booth.",
      price: 45000,
      rating: 4.9,
      reviewCount: 38,
      location: "MG Road",
      duration: "Full day coverage",
      capacity: "Any",
      featured: true,
      image: "/placeholder.svg?height=300&width=500&text=Cinematic+Moments",
      images: [
        "/placeholder.svg?height=600&width=800&text=Cinematic+Sample+1",
        "/placeholder.svg?height=600&width=800&text=Cinematic+Sample+2",
        "/placeholder.svg?height=600&width=800&text=Cinematic+Sample+3",
        "/placeholder.svg?height=600&width=800&text=Cinematic+Sample+4",
      ],
      reviews: [],
    },
    {
      id: "8",
      name: "Tamarind Tree",
      category: "halls",
      description:
        "Beautiful heritage venue with garden views, elegant spaces, and dedicated bridal suite in Bangalore. Perfect for ceremonies and receptions with a touch of history.",
      price: 200000,
      rating: 4.7,
      reviewCount: 42,
      location: "Yelahanka",
      duration: "Full day",
      capacity: "300",
      featured: true,
      image: "/placeholder.svg?height=300&width=500&text=Tamarind+Tree",
      images: [
        "/placeholder.svg?height=600&width=800&text=Tamarind+Tree+1",
        "/placeholder.svg?height=600&width=800&text=Tamarind+Tree+2",
        "/placeholder.svg?height=600&width=800&text=Tamarind+Tree+3",
        "/placeholder.svg?height=600&width=800&text=Tamarind+Tree+4",
      ],
      reviews: [],
    },
    {
      id: "9",
      name: "Royal Decor",
      category: "decorators",
      description:
        "Luxury decoration services for high-end events in Bangalore. Includes elaborate floral arrangements, custom lighting, premium linens, and personalized decor elements.",
      price: 75000,
      rating: 4.8,
      reviewCount: 31,
      location: "Sadashivanagar",
      duration: "Setup day before event",
      capacity: "Any",
      featured: true,
      image: "/placeholder.svg?height=300&width=500&text=Royal+Decor",
      images: [
        "/placeholder.svg?height=600&width=800&text=Royal+Decor+1",
        "/placeholder.svg?height=600&width=800&text=Royal+Decor+2",
        "/placeholder.svg?height=600&width=800&text=Royal+Decor+3",
        "/placeholder.svg?height=600&width=800&text=Royal+Decor+4",
      ],
      reviews: [],
    },
    {
      id: "10",
      name: "Corporate Lens",
      category: "cameras",
      description:
        "Specialized photography services for corporate events, product launches, and conferences in Bangalore. Includes professional editing and quick turnaround.",
      price: 30000,
      rating: 4.4,
      reviewCount: 19,
      location: "Electronic City",
      duration: "As needed",
      capacity: "Any",
      featured: false,
      image: "/placeholder.svg?height=300&width=500&text=Corporate+Lens",
      images: [
        "/placeholder.svg?height=600&width=800&text=Corporate+Photo+1",
        "/placeholder.svg?height=600&width=800&text=Corporate+Photo+2",
        "/placeholder.svg?height=600&width=800&text=Corporate+Photo+3",
        "/placeholder.svg?height=600&width=800&text=Corporate+Photo+4",
      ],
      reviews: [],
    },
    {
      id: "11",
      name: "Lalbagh Garden Party Venue",
      category: "halls",
      description:
        "Beautiful outdoor venue near Lalbagh Botanical Garden, perfect for daytime events and summer parties in Bangalore. Includes covered areas in case of rain.",
      price: 80000,
      rating: 4.6,
      reviewCount: 25,
      location: "Lalbagh",
      duration: "Full day",
      capacity: "150",
      featured: false,
      image: "/placeholder.svg?height=300&width=500&text=Lalbagh+Garden+Venue",
      images: [
        "/placeholder.svg?height=600&width=800&text=Garden+Venue+1",
        "/placeholder.svg?height=600&width=800&text=Garden+Venue+2",
        "/placeholder.svg?height=600&width=800&text=Garden+Venue+3",
        "/placeholder.svg?height=600&width=800&text=Garden+Venue+4",
      ],
      reviews: [],
    },
    {
      id: "12",
      name: "Bangalore Theme Decorators",
      category: "decorators",
      description:
        "Custom themed decorations for special events in Bangalore. From traditional Karnataka themes to futuristic designs, we create immersive environments that match your vision.",
      price: 50000,
      rating: 4.7,
      reviewCount: 33,
      location: "Malleshwaram",
      duration: "Setup 1-2 days before event",
      capacity: "Any",
      featured: false,
      image: "/placeholder.svg?height=300&width=500&text=Theme+Decorators",
      images: [
        "/placeholder.svg?height=600&width=800&text=Theme+Decor+1",
        "/placeholder.svg?height=600&width=800&text=Theme+Decor+2",
        "/placeholder.svg?height=600&width=800&text=Theme+Decor+3",
        "/placeholder.svg?height=600&width=800&text=Theme+Decor+4",
      ],
      reviews: [],
    },
  ].map((service) => ({
    ...service,
    description: service.description.replace(/ in Bangalore/g, ""),
    location: service.location.replace(/, Bangalore/g, ""),
  }))
}

export function getFeaturedServices() {
  const services = getServices()
  return services.filter((service) => service.featured)
}

export function getServiceById(id: string) {
  const services = getServices()
  return services.find((service) => service.id === id)
}
